name: Deploy

on:
  push:
    branches: ['master']

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: build
        env:
          BASE_PATH: '/credit-calculator'
        run: |
          echo success
          
